apiVersion: v1
kind: Service
metadata:
  name: my-microservice
spec:
  selector:
    app: my-microservice
  ports:
    - protocol: TCP
      port: 80           # Port on the service
      targetPort: 8080    # Port on the container
  type: LoadBalancer      # Exposes the service externally (for cloud environments)

